server:
  port: 8082
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tmcheckersystem@gmail.com
    password: VpA/s&5T].Pd,[^`
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  application:
    name: Peoples Application
#  datasource:
#    url: jdbc:mysql://localhost/tmchecking?serverTimezone=UTC
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://162.241.219.101:3306/lilcpand_tmchecking?serverTimezone=UTC
    username: lilcpand_tmcheck
    password: cs@Project544
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
scheduledEmailCron: '0 0/2 * * * *'